import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navbar from "../components/navbar";
import granvilleImage from "../assets/index/granville island photo.jpg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="h-screen snap-y snap-mandatory overflow-scroll">
        <section className="snap-start">
          <Navbar />
          <section className="flex h-screen justify-center bg-fixed">
            <div className="m-auto text-3xl md:columns-1 text-center">
              <h1>hi, my name is 顾恒同, but you can call me maggie... </h1>
            </div>
          </section>
        </section>

        <section className="md:columns-2 h-screen bg-fixed snap-start sm: columns-1">
          <div className="h-full flex items-center content-center justify-center break-inside-avoid-column">
            <div className="p-16">
              {/* <h1 className="mx-auto">the basics</h1> */}

              <h3 className="p-3 text-xl"> 👶 born in shanghai </h3>
              <h3 className="p-3 text-xl">
                {" "}
                👧 raised in vancouver & kamloops
              </h3>
              <h3 className="p-3 text-xl">
                {" "}
                👩‍🎓 currently @ ubc studying computer engineering
              </h3>
              <h3 className="p-3 text-xl">
                💗 interests: cooking new recipes, trying new restaurants,
                making new memories & solving problems
              </h3>

              <div className="pt-8 pl-5">
                <button
                  type="button"
                  className="float-left text-pink-900 bg-white border border-gray-300 focus:outline-none hover:bg-slate-400 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-stone-100 dark:text-slate-400 dark:border-stone-100 dark:hover:bg-slate-600 dark:hover:border-slate-600 dark:focus:ring-gray-700"
                >
                  Resume
                </button>
              </div>
            </div>
          </div>
          <div className="flex items-center h-full h-screen content-center justify-center inline-block">
            <Image
              src={granvilleImage}
              alt="selfie"
              className=" mx-auto w-1/2"
            />
          </div>
        </section>

        <section className="snap-start md:columns-1 h-screen bg-fixed justify-center flex p-8 ">
          <div className="m-auto">
            <ol className="relative border-l border-gray-200 dark:border-gray-300">
              <li className="mb-10 ml-4">
                <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                  September 2019 - May 2020
                </time>
                {/* <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                Application UI code in Tailwind CSS
              </h3> */}
                <p className="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">
                  Completed a general first year in Engineering.
                </p>
              </li>
              <li className="mb-10 ml-4">
                <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                  June 2020 - August 2020
                </time>

                <p className="text-base font-normal text-gray-500 dark:text-gray-400">
                  Internship at EHD Consulting in Kamloops, BC
                </p>
              </li>

              <li className="mb-10 ml-4">
                <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                  September 2020 - April 2021
                </time>
                <p className="text-base font-normal text-gray-500 dark:text-gray-400">
                  Completed second year of Civil Engineering (First Choice
                  Major) & started taking computer science classes
                </p>
              </li>

              <li className="mb-10 ml-4">
                <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                  May 2021 - August 2021
                </time>

                <p className="text-base font-normal text-gray-500 dark:text-gray-400">
                  Co-op at Springline as Project Coordinator on Salmon Arm West
                  Highway 1 project
                </p>
              </li>

              <li className="mb-10 ml-4">
                <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                  September 2021 - January 2022
                </time>

                <p className="text-base font-normal text-gray-500 dark:text-gray-400">
                  Completed half of third year of Civil Engineering
                </p>
              </li>

              <li className="mb-10 ml-4">
                <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                  February 2022 - August 2022
                </time>

                <p className="text-base font-normal text-gray-500 dark:text-gray-400">
                  Co-op at Tesla Motors as Project Management Intern
                </p>
              </li>

              <li className="mb-10 ml-4">
                <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                  September 2022 - Present
                </time>

                <p className="text-base font-normal text-gray-500 dark:text-gray-400">
                  Switched into Computer Engineering. Anticipated graduation
                  date of May 2024
                </p>
              </li>
            </ol>
          </div>
        </section>

        <section className="md:columns-2 h-screen bg-fixed snap-start sm: columns-1">
          <h1 className="m-auto text-3xl justify-center flex h-full items-center">
            why does this exist?
          </h1>
          <div className="m-auto break-inside-avoid-column">
            <h3 className="text-xl justify-center ">
              a) exists as a place to collate some of my thoughts & works{" "}
              <br></br>
              b) wanted to build a new website <br></br>
              c) document my learning & recruitement process
            </h3>
          </div>
        </section>
      </main>
    </>
  );
}
